# Generated by Django 4.2.9 on 2026-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniorprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
